In [1]:
import pandas as pd

districts = pd.read_csv("../data/raw/outbreaks/district_master.csv")

years = list(range(2015, 2025))

rows = []

for _, row in districts.iterrows():
    for year in years:
        rows.append({
            "State": row["State"],
            "District": row["District"],
            "Latitude": row["Latitude"],
            "Longitude": row["Longitude"],
            "Year": year
        })

environment_df = pd.DataFrame(rows)

environment_df.head()

       State    District  Latitude  Longitude  Year
0  Karnataka  Shivamogga   13.9299    75.5681  2015
1  Karnataka  Shivamogga   13.9299    75.5681  2016
2  Karnataka  Shivamogga   13.9299    75.5681  2017
3  Karnataka  Shivamogga   13.9299    75.5681  2018
4  Karnataka  Shivamogga   13.9299    75.5681  2019

In [3]:
print(environment_df.shape)

(90, 5)

In [4]:
environment_df["Temperature"] = None
environment_df["Rainfall"] = None
environment_df["Humidity"] = None
environment_df["NDVI"] = None
environment_df["Forest_Loss"] = None
environment_df["Elevation"] = None

environment_df.head()

,State,District,Latitude,Longitude,Year,Temperature,Rainfall,Humidity,NDVI,Forest_Loss,Elevation
0,Karnataka,Shivamogga,13.9299,75.5681,2015,None,None,None,None,None,None
1,Karnataka,Shivamogga,13.9299,75.5681,2016,None,None,None,None,None,None
2,Karnataka,Shivamogga,13.9299,75.5681,2017,None,None,None,None,None,None
3,Karnataka,Shivamogga,13.9299,75.5681,2018,None,None,None,None,None,None
4,Karnataka,Shivamogga,13.9299,75.5681,2019,None,None,None,None,None,None

In [2]:
environment_df.to_csv(
    "../data/interim/environmental_dataset.csv",
    index=False
)

print("Environmental dataset created successfully!")

Environmental dataset created successfully!