In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [3]:
master = pd.read_csv(
    "../data/processed/master_environment_dataset.csv"
)

master.head()

,State,District,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI
0,Karnataka,Shivamogga,2021,24.506868,13.2,37.2,1779.7,8.926923,1010.807967,0.019144,677.877599,0.586866
1,Karnataka,Shivamogga,2022,24.796006,12.8,37.0,1452.4,9.242424,1010.384298,0.019144,677.877599,0.586866
2,Karnataka,Shivamogga,2023,25.862466,13.0,39.3,751.4,11.691781,1011.566575,0.019144,677.877599,0.586866
3,Karnataka,Shivamogga,2024,25.993820,13.9,41.0,1359.0,10.768820,1010.710112,0.019144,677.877599,0.586866
4,Karnataka,Uttara Kannada,2015,27.601681,20.4,35.5,3006.5,NaN,NaN,0.008988,429.982021,0.586866

In [4]:
print(master.shape)

master.info()

master.describe()

(78, 12)
<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State            78 non-null     str
 1   District         78 non-null     str
 2   Year             78 non-null     int64
 3   Temperature      78 non-null     float64
 4   Min_Temperature  78 non-null     float64
 5   Max_Temperature  78 non-null     float64
 6   Rainfall         78 non-null     float64
 7   wspd             54 non-null     float64
 8   pres             44 non-null     float64
 9   Forest_Loss      78 non-null     float64
 10  Elevation        78 non-null     float64
 11  NDVI             78 non-null     float64
dtypes: float64(9), int64(1), str(2)
memory usage: 8.7 KB

,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI
count,78.000000,78.000000,78.000000,78.000000,78.000000,54.000000,44.000000,78.000000,78.000000,7.800000e+01
mean,2019.807692,27.424320,18.296154,36.706410,2846.585897,10.236246,1010.218524,0.011157,372.259762,5.868660e-01
std,2.910160,1.817312,2.924036,1.750424,878.105244,2.621311,1.213591,0.006268,273.004381,1.408886e-16
min,2015.000000,20.748626,10.700000,31.800000,4.100000,5.897338,1008.741047,0.003779,71.222575,5.868660e-01
25%,2017.000000,27.527527,17.000000,36.050000,2317.575000,8.333329,1009.266038,0.004742,99.188848,5.868660e-01
50%,2020.000000,27.919543,18.100000,36.800000,2887.550000,9.943332,1009.976558,0.008988,211.357774,5.868660e-01
75%,2022.000000,28.402758,20.375000,37.175000,3298.850000,11.608699,1010.798410,0.016563,651.723530,5.868660e-01
max,2024.000000,30.150000,25.400000,42.100000,4865.300000,15.889863,1013.160274,0.021077,890.594716,5.868660e-01

In [7]:
numeric_cols = master.select_dtypes(include=["number"]).columns

imputer = SimpleImputer(strategy="median")

master[numeric_cols] = imputer.fit_transform(master[numeric_cols])

In [8]:
print(master.isnull().sum())

State              0
District           0
Year               0
Temperature        0
Min_Temperature    0
Max_Temperature    0
Rainfall           0
wspd               0
pres               0
Forest_Loss        0
Elevation          0
NDVI               0
dtype: int64

In [11]:
state_encoder = LabelEncoder()
district_encoder = LabelEncoder()

master["State_ID"] = state_encoder.fit_transform(master["State"])
master["District_ID"] = district_encoder.fit_transform(master["District"])

In [12]:
master["Temp_Range"] = (
    master["Max_Temperature"]
    - master["Min_Temperature"]
)

master["Rainfall_per_Elevation"] = (
    master["Rainfall"]
    / (master["Elevation"] + 1)
)

master["Vegetation_Forest_Index"] = (
    master["NDVI"]
    * (1 - master["Forest_Loss"])
)

In [13]:
master.describe()

,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI,State_ID,District_ID,Temp_Range,Rainfall_per_Elevation,Vegetation_Forest_Index
count,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,7.800000e+01,78.000000,78.000000,78.000000,78.000000,78.000000
mean,2019.807692,27.424320,18.296154,36.706410,2846.585897,10.146119,1010.113051,0.011157,372.259762,5.868660e-01,1.256410,4.307692,18.410256,16.798630,0.580318
std,2.910160,1.817312,2.924036,1.750424,878.105244,2.179011,0.914908,0.006268,273.004381,1.408886e-16,0.986084,2.539597,3.198644,15.568298,0.003679
min,2015.000000,20.748626,10.700000,31.800000,4.100000,5.897338,1008.741047,0.003779,71.222575,5.868660e-01,0.000000,0.000000,9.800000,0.005996,0.574496
25%,2017.000000,27.527527,17.000000,36.050000,2317.575000,9.242337,1009.587569,0.004742,99.188848,5.868660e-01,0.250000,2.000000,16.325000,4.654506,0.577146
50%,2020.000000,27.919543,18.100000,36.800000,2887.550000,9.943332,1009.976558,0.008988,211.357774,5.868660e-01,1.000000,5.000000,18.450000,11.093729,0.581591
75%,2022.000000,28.402758,20.375000,37.175000,3298.850000,10.722443,1010.067252,0.016563,651.723530,5.868660e-01,2.000000,6.750000,19.950000,24.657236,0.584083
max,2024.000000,30.150000,25.400000,42.100000,4865.300000,15.889863,1013.160274,0.021077,890.594716,5.868660e-01,3.000000,8.000000,27.100000,59.726477,0.584648

In [15]:
scaler = StandardScaler()

columns_to_scale = [
    "Temperature",
    "Rainfall",
    "NDVI",
    "Forest_Loss",
    "Elevation"
]

scaled = scaler.fit_transform(master[columns_to_scale])

scaled_df = pd.DataFrame(
    scaled,
    columns=[c + "_Scaled" for c in columns_to_scale]
)

master = pd.concat(
    [master, scaled_df],
    axis=1
)

In [16]:
correlation = master.select_dtypes(
    include=np.number
).corr()

correlation

,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI,State_ID,District_ID,Temp_Range,Rainfall_per_Elevation,Vegetation_Forest_Index,Temperature_Scaled,Rainfall_Scaled,NDVI_Scaled,Forest_Loss_Scaled,Elevation_Scaled
Year,1.000000,-0.422578,-0.457641,0.007129,0.076240,0.575910,0.230118,0.126982,0.161624,-0.146106,-0.027850,-0.097323,0.422253,-0.012567,-0.126982,-0.422578,0.076240,-0.162742,0.126982,0.161624
Temperature,-0.422578,1.000000,0.760520,0.528701,0.092823,0.051159,-0.605478,-0.425857,-0.442608,0.252859,-0.007985,0.005115,-0.405902,0.356023,0.425857,1.000000,0.092823,0.256719,-0.425857,-0.442608
Min_Temperature,-0.457641,0.760520,1.000000,0.135069,0.231826,-0.166674,-0.539601,-0.076393,-0.193259,0.213239,0.086376,0.081135,-0.840234,0.157876,0.076393,0.760520,0.231826,0.259533,-0.076393,-0.193259
Max_Temperature,0.007129,0.528701,0.135069,1.000000,-0.308592,0.206806,-0.024762,-0.057208,-0.027382,0.180885,-0.068681,-0.257831,0.423766,0.057230,0.057208,0.528701,-0.308592,0.209365,-0.057208,-0.027382
Rainfall,0.076240,0.092823,0.231826,-0.308592,1.000000,-0.035993,-0.451587,-0.300207,-0.339249,-0.161161,-0.011951,0.136751,-0.380797,0.443100,0.300207,0.092823,1.000000,-0.152711,-0.300207,-0.339249
wspd,0.575910,0.051159,-0.166674,0.206806,-0.035993,1.000000,0.023327,-0.305570,-0.143092,-0.038368,-0.196356,-0.034171,0.265538,0.027997,0.305570,0.051159,-0.035993,-0.019436,-0.305570,-0.143092
pres,0.230118,-0.605478,-0.539601,-0.024762,-0.451587,0.023327,1.000000,0.577679,0.633072,-0.072717,0.014905,-0.286790,0.479724,-0.484681,-0.577679,-0.605478,-0.451587,-0.041241,0.577679,0.633072
Forest_Loss,0.126982,-0.425857,-0.076393,-0.057208,-0.300207,-0.305570,0.577679,1.000000,0.842111,-0.087110,0.050773,-0.263550,0.038528,-0.505529,-1.000000,-0.425857,-0.300207,-0.052763,1.000000,0.842111
Elevation,0.161624,-0.442608,-0.193259,-0.027382,-0.339249,-0.143092,0.633072,0.842111,1.000000,-0.077252,-0.000406,0.085860,0.161682,-0.815990,-0.842111,-0.442608,-0.339249,-0.003757,0.842111,1.000000
NDVI,-0.146106,0.252859,0.213239,0.180885,-0.161161,-0.038368,-0.072717,-0.087110,-0.077252,1.000000,-0.019029,-0.114702,-0.091233,-0.000303,0.090251,0.249462,-0.159816,0.951952,-0.090251,-0.079755
State_ID,-0.027850,-0.007985,0.086376,-0.068681,-0.011951,-0.196356,0.014905,0.050773,-0.000406,-0.019029,1.000000,0.071806,-0.116545,-0.067306,-0.050773,-0.007985,-0.011951,-0.054851,0.050773,-0.000406
District_ID,-0.097323,0.005115,0.081135,-0.257831,0.136751,-0.034171,-0.286790,-0.263550,0.085860,-0.114702,0.071806,1.000000,-0.215265,-0.396160,0.263550,0.005115,0.136751,-0.087853,-0.263550,0.085860
Temp_Range,0.422253,-0.405902,-0.840234,0.423766,-0.380797,0.265538,0.479724,0.038528,0.161682,-0.091233,-0.116545,-0.215265,1.000000,-0.113003,-0.038528,-0.405902,-0.380797,-0.122679,0.038528,0.161682
Rainfall_per_Elevation,-0.012567,0.356023,0.157876,0.057230,0.443100,0.027997,-0.484681,-0.505529,-0.815990,-0.000303,-0.067306,-0.396160,-0.113003,1.000000,0.505529,0.356023,0.443100,-0.069693,-0.505529,-0.815990
Vegetation_Forest_Index,-0.126982,0.425857,0.076393,0.057208,0.300207,0.305570,-0.577679,-1.000000,-0.842111,0.090251,-0.050773,0.263550,-0.038528,0.505529,1.000000,0.425857,0.300207,0.052763,-1.000000,-0.842111
Temperature_Scaled,-0.422578,1.000000,0.760520,0.528701,0.092823,0.051159,-0.605478,-0.425857,-0.442608,0.249462,-0.007985,0.005115,-0.405902,0.356023,0.425857,1.000000,0.092823,0.256719,-0.425857,-0.442608
Rainfall_Scaled,0.076240,0.092823,0.231826,-0.308592,1.000000,-0.035993,-0.451587,-0.300207,-0.339249,-0.159816,-0.011951,0.136751,-0.380797,0.443100,0.300207,0.092823,1.000000,-0.152711,-0.300207,-0.339249
NDVI_Scaled,-0.162742,0.256719,0.259533,0.209365,-0.152711,-0.019436,-0.041241,-0.052763,-0.003757,0.951952,-0.054851,-0.087853,-0.122679,-0.069693,0.052763,0.256719,-0.152711,1.000000,-0.052763,-0.003757
Forest_Loss_Scaled,0.126982,-0.425857,-0.076393,-0.057208,-0.300207,-0.305570,0.577679,1.000000,0.842111,-0.090251,0.050773,-0.263550,0.038528,-0.505529,-1.000000,-0.425857,-0.300207,-0.052763,1.000000,0.842111
Elevation_Scaled,0.161624,-0.442608,-0.193259,-0.027382,-0.339249,-0.143092,0.633072,0.842111,1.000000,-0.079755,-0.000406,0.085860,0.161682,-0.815990,-0.842111,-0.442608,-0.339249,-0.003757,0.842111,1.000000

In [17]:
print(master.describe())

print(master.columns.tolist())

              Year  Temperature  Min_Temperature  Max_Temperature  \
count    78.000000    78.000000        78.000000        78.000000
mean   2019.807692    27.424320        18.296154        36.706410
std       2.910160     1.817312         2.924036         1.750424
min    2015.000000    20.748626        10.700000        31.800000
25%    2017.000000    27.527527        17.000000        36.050000
50%    2020.000000    27.919543        18.100000        36.800000
75%    2022.000000    28.402758        20.375000        37.175000
max    2024.000000    30.150000        25.400000        42.100000

          Rainfall       wspd         pres  Forest_Loss   Elevation  \
count    78.000000  78.000000    78.000000    78.000000   78.000000
mean   2846.585897  10.146119  1010.113051     0.011157  372.259762
std     878.105244   2.179011     0.914908     0.006268  273.004381
min       4.100000   5.897338  1008.741047     0.003779   71.222575
25%    2317.575000   9.242337  1009.587569     0.004742   99.188848
50%    2887.550000   9.943332  1009.976558     0.008988  211.357774
75%    3298.850000  10.722443  1010.067252     0.016563  651.723530
max    4865.300000  15.889863  1013.160274     0.021077  890.594716

               NDVI   State_ID  District_ID  Temp_Range  \
count  7.800000e+01  78.000000    78.000000   78.000000
mean   5.868660e-01   1.256410     4.307692   18.410256
std    1.408886e-16   0.986084     2.539597    3.198644
min    5.868660e-01   0.000000     0.000000    9.800000
25%    5.868660e-01   0.250000     2.000000   16.325000
50%    5.868660e-01   1.000000     5.000000   18.450000
75%    5.868660e-01   2.000000     6.750000   19.950000
max    5.868660e-01   3.000000     8.000000   27.100000

       Rainfall_per_Elevation  Vegetation_Forest_Index  Temperature_Scaled  \
count               78.000000                78.000000        7.800000e+01
mean                16.798630                 0.580318       -5.551115e-16
std                 15.568298                 0.003679        1.006473e+00
min                  0.005996                 0.574496       -3.697165e+00
25%                  4.654506                 0.577146        5.715841e-02
50%                 11.093729                 0.581591        2.742664e-01
75%                 24.657236                 0.584083        5.418831e-01
max                 59.726477                 0.584648        1.509549e+00

       Rainfall_Scaled   NDVI_Scaled  Forest_Loss_Scaled  Elevation_Scaled
count     7.800000e+01  7.800000e+01        7.800000e+01      7.800000e+01
mean     -1.366428e-16 -8.824850e-17        7.913897e-16     -4.810966e-16
std       1.006473e+00  1.093647e-16        1.006473e+00      1.006473e+00
min      -3.258020e+00 -2.220446e-16       -1.184724e+00     -1.109820e+00
25%      -6.063453e-01 -2.220446e-16       -1.030176e+00     -1.006718e+00
50%       4.695251e-02  0.000000e+00       -3.483612e-01     -5.931899e-01
75%       5.183791e-01  0.000000e+00        8.680120e-01      1.030286e+00
max       2.313823e+00  0.000000e+00        1.592787e+00      1.910921e+00
['State', 'District', 'Year', 'Temperature', 'Min_Temperature', 'Max_Temperature', 'Rainfall', 'wspd', 'pres', 'Forest_Loss', 'Elevation', 'NDVI', 'State_ID', 'District_ID', 'Temp_Range', 'Rainfall_per_Elevation', 'Vegetation_Forest_Index', 'Temperature_Scaled', 'Rainfall_Scaled', 'NDVI_Scaled', 'Forest_Loss_Scaled', 'Elevation_Scaled']

In [18]:
master.to_csv(
    "../data/processed/master_features.csv",
    index=False
)

print("Feature engineering complete!")

Feature engineering complete!